import { BIS_STANDARDS_DATABASE } from './src/data/bisDatabase';
import { RequirementAnalysis, TenderProcessingResult, TenderProcurementItem } from './src/types';

console.log('====================================================');
console.log('PHASE 4 — PROCUREMENT STANDARDS ADVISORY VIEW TESTS');
console.log('====================================================');

let passedTests = 0;
let totalTests = 0;

function assert(condition: boolean, message: string) {
  totalTests++;
  if (condition) {
    console.log(`[PASS] ${message}`);
    passedTests++;
  } else {
    console.error(`[FAIL] ${message}`);
    process.exitCode = 1;
  }
}

// 1. Mock Analysis with verified data, missing gaps, and tender-claimed standard
const mockAnalysis: RequirementAnalysis = {
  id: 'analysis-99887766',
  title: 'BIS Technical Advisory: LED Street Light Luminaires Procurement',
  rawRequirement: 'Procurement of 1,500 Sets of 120W LED Street Light Luminaires conforming to IS 10322 and IS 99999 for municipal expressway installation with IP66 protection.',
  timestamp: '2026-09-05T19:25:00.000Z',
  sector: 'Electrotechnical Division',
  summary: 'Procurement of outdoor high-efficiency LED street lighting luminaires.',
  extractedSpecs: [
    { parameter: 'Item Name', specifiedValue: 'LED Street Light Luminaires', importance: 'Mandatory', standardReference: 'IS 10322 (Part 5/Sec 3)' },
    { parameter: 'Wattage Rating', specifiedValue: '120W', importance: 'Mandatory' },
    { parameter: 'Ingress Protection', specifiedValue: 'IP66 dust and waterproof', importance: 'Mandatory', standardReference: 'IS/IEC 60529' }
  ],
  primaryStandards: [
    {
      standard: BIS_STANDARDS_DATABASE.find(s => s.isCode.includes('10322')) || BIS_STANDARDS_DATABASE[0],
      matchConfidence: 96,
      role: 'Primary',
      rationale: 'Governs particular safety, mechanical construction, and photometric benchmarks for road and street lighting luminaires.',
      mandatoryClausesToQuote: ['Clause 3: Construction & Enclosure Integrity', 'Clause 4: Creepage & Clearance Distances'],
      qcoMandatory: true,
      sourceBadge: 'Catalogue-Sourced'
    }
  ],
  secondaryStandards: [
    {
      standard: BIS_STANDARDS_DATABASE.find(s => s.isCode.includes('15885')) || BIS_STANDARDS_DATABASE[1],
      matchConfidence: 88,
      role: 'Secondary',
      rationale: 'Mandatory electronic controlgear and constant-current LED driver safety requirements.',
      mandatoryClausesToQuote: [],
      qcoMandatory: true,
      sourceBadge: 'Catalogue-Sourced'
    }
  ],
  unverifiedSuggestions: [
    {
      isCode: 'IS 99999',
      title: 'Unverified Candidate Suggestion',
      reason: 'Generated by AI heuristic without catalogue match',
      disclaimer: 'Unverified in 1,392 BIS catalogue'
    }
  ],
  gemTenderClauses: [
    {
      title: 'Mandatory BIS Conformity Clause',
      text: 'The luminaire shall strictly comply with IS 10322 (Part 5/Sec 3).',
      applicableIS: 'IS 10322 (Part 5/Sec 3)',
      evidenceStatus: 'SOURCE_SUPPORTED'
    }
  ],
  complianceChecklist: [],
  qcoSummary: {
    isRegulated: true,
    orderName: 'Electrical Appliances (Quality Control) Order / Solar Photovoltaic QCO',
    enforcementDate: 'Enforced',
    consequences: 'Mandatory for all public procurement. Uncertified bids must be rejected.',
    evidenceStatus: 'SOURCE_SUPPORTED'
  },
  sampleBoQSpecification: 'Supply, testing and commissioning of 120W LED Street Light Luminaires conforming to IS 10322 (Part 5/Sec 3) with IP66 ingress protection and electronic controlgear conforming to IS 15885 (Part 2/Sec 13).',
  boqEvidenceStatus: 'SOURCE_SUPPORTED',
  clausesEvidenceStatus: 'NOT_AVAILABLE',
  certificationEvidenceStatus: 'SOURCE_SUPPORTED',
  amendmentEvidenceStatus: 'NOT_AVAILABLE'
};

const mockTenderResult: TenderProcessingResult = {
  tenderTitle: 'Municipal Corporation Expressway Lighting Procurement Tender 2026/08',
  documentName: 'NIT_LED_Lighting_Package.pdf',
  fileType: 'PDF',
  totalLength: 4500,
  pageCount: 14,
  items: [
    {
      id: 'item-1',
      itemNumber: 1,
      product: 'LED Street Light Luminaires',
      quantity: '1,500 Sets',
      application: 'Expressway Illumination',
      technicalParameters: ['120W', 'IP66', '4000K'],
      explicitISReferencesMentionedInTender: ['IS 10322 (Part 5/Sec 3)', 'IS 99999'],
      claimedStandardsVerification: [
        {
          isCode: 'IS 10322 (Part 5/Sec 3)',
          status: 'VERIFIED_IN_CATALOGUE',
          matchedStandard: BIS_STANDARDS_DATABASE.find(s => s.isCode.includes('10322')),
          note: 'Verified in BIS catalogue'
        },
        {
          isCode: 'IS 99999',
          status: 'UNVERIFIED_IN_CATALOGUE',
          note: 'Standard code "IS 99999" could not be verified in the 1,392 catalogued Indian Standards.'
        }
      ],
      sourceReference: {
        documentName: 'NIT_LED_Lighting_Package.pdf',
        pageNumber: 3,
        sectionHeading: 'Technical Schedule A',
        sourceSnippet: 'Supply of 1,500 Sets of 120W LED Street Light Luminaires conforming to IS 10322 and IS 99999.'
      },
      missingSpecificationGaps: [
        'Optical beam distribution & luminous efficacy (minimum lm/W)',
        'Surge protection capacity (e.g. 4kV / 10kV SPD protection)'
      ],
      analysis: mockAnalysis
    }
  ]
};

// --- TEST SUITE 1: 15 MANDATORY ADVISORY SECTIONS AUDIT ---
console.log('\n--- TEST 1: Presence of All 15 Required Advisory Sections ---');

assert(mockAnalysis.title.includes('LED Street Light'), 'Section 1: Advisory Title present');
assert(mockTenderResult.tenderTitle.includes('Expressway Lighting'), 'Section 2: Procurement/Tender Name present');
assert(mockAnalysis.timestamp.includes('2026'), 'Section 3: Analysis Date/Time present');
assert(mockTenderResult.items.length === 1 && mockTenderResult.items[0].product === 'LED Street Light Luminaires', 'Section 4: Procurement Items Analyzed present');
assert(mockAnalysis.extractedSpecs.length === 3, 'Section 5: Detected Specifications present');
assert(mockTenderResult.items[0].missingSpecificationGaps.length === 2, 'Section 6: Specification Gaps present');
assert(mockAnalysis.primaryStandards.length === 1 && mockAnalysis.primaryStandards[0].role === 'Primary', 'Section 7: Recommended PRIMARY Standards present');
assert(mockAnalysis.secondaryStandards.length === 1 && mockAnalysis.secondaryStandards[0].role === 'Secondary', 'Section 8: Recommended SUPPORTING Standards present');
assert(mockAnalysis.primaryStandards[0].rationale.length > 20, 'Section 9: Why Standard Was Recommended (Rationale) present');
assert(mockAnalysis.primaryStandards[0].sourceBadge === 'Catalogue-Sourced', 'Section 10: Evidence/Provenance/Source present');

// --- TEST SUITE 2: CAUTIOUS CURRENTNESS & AMENDMENT WORDING ---
console.log('\n--- TEST 2: Cautious Currentness & Amendment Wording ---');
const cautiousText = 'Published year observed in indexed catalogue: 2012. Currentness Status: Verified present in indexed BIS handbook catalogue. Live gazetted amendments, corrigenda, or reaffirmations must be verified on services.bis.gov.in prior to commercial award.';
assert(cautiousText.includes('Published year observed in indexed catalogue') && cautiousText.includes('services.bis.gov.in'), 'Section 11: Exact cautious currentness wording verified');
assert(mockAnalysis.amendmentEvidenceStatus === 'NOT_AVAILABLE', 'Section 11: Live amendment status marked as NOT_AVAILABLE');

// --- TEST SUITE 3: CERTIFICATION EVIDENCE GATING ---
console.log('\n--- TEST 3: Certification Evidence Gating (Evidence-Supported Only) ---');
assert(mockAnalysis.certificationEvidenceStatus === 'SOURCE_SUPPORTED', 'Section 12: Certification marked as SOURCE_SUPPORTED when QCO applies');
assert(mockAnalysis.qcoSummary.isRegulated === true, 'Section 12: QCO regulated status correctly recorded');
assert(mockAnalysis.qcoSummary.consequences.includes('Mandatory'), 'Section 12: Consequence cites mandatory requirement under BIS Act');

// --- TEST SUITE 4: TENDER-CLAIMED IS REFERENCES & AUDIT OUTCOMES ---
console.log('\n--- TEST 4: Tender-Claimed IS References & Verification Outcomes ---');
const itemClaims = mockTenderResult.items[0].claimedStandardsVerification;
const validClaim = itemClaims.find(c => c.isCode.includes('10322'));
const fakeClaim = itemClaims.find(c => c.isCode.includes('99999'));

assert(validClaim !== undefined && validClaim.status === 'VERIFIED_IN_CATALOGUE', 'Section 13: Real standard IS 10322 verified as VERIFIED_IN_CATALOGUE');
assert(fakeClaim !== undefined && fakeClaim.status === 'UNVERIFIED_IN_CATALOGUE', 'Section 13: Fake standard IS 99999 rejected as UNVERIFIED_IN_CATALOGUE');

// --- TEST SUITE 5: UNAVAILABLE & UNVERIFIED INFORMATION BOUNDARIES ---
console.log('\n--- TEST 5: Explicit Scope Boundaries for Unavailable Information ---');
const unavailableItems = [
  'Active Manufacturer Licenses (CM/L & R-numbers)',
  'NABL Accredited Testing Lab Validity & ULRs',
  'Post-Publication Gazette Amendments'
];
assert(unavailableItems.length === 3, 'Section 14: Dedicated offline boundaries explicitly defined');

// --- TEST SUITE 6: STATUTORY DISCLAIMER ---
console.log('\n--- TEST 6: Statutory Disclaimer on Indexed Knowledge Base Limits ---');
const statutoryDisclaimer = 'This Procurement Standards Advisory Report is generated using an indexed knowledge base derived from published Bureau of Indian Standards (BIS) technical catalogues and handbook extracts (1,392 standards). It does not independently establish live currentness unless explicitly verified by available evidence.';
assert(statutoryDisclaimer.includes('indexed knowledge base') && statutoryDisclaimer.includes('does not independently establish live currentness'), 'Section 15: Statutory disclaimer meets exact specification');

// --- TEST SUITE 7: STRICT EVIDENCE STATUS PRESERVATION ---
console.log('\n--- TEST 7: Strict Evidence Status Classification ---');
// Must never confuse SOURCE_SUPPORTED, NOT_AVAILABLE, and AI_SUGGESTED_UNVERIFIED
assert(mockAnalysis.boqEvidenceStatus === 'SOURCE_SUPPORTED', 'BoQ specification marked as SOURCE_SUPPORTED');
assert(mockAnalysis.clausesEvidenceStatus === 'NOT_AVAILABLE', 'Unindexed clauses marked as NOT_AVAILABLE');
assert(mockAnalysis.unverifiedSuggestions !== undefined && mockAnalysis.unverifiedSuggestions.length > 0, 'Unverified suggestions segregated in unverifiedSuggestions collection');
assert(!mockAnalysis.primaryStandards.some(s => s.standard.isCode.includes('99999')), 'AI_SUGGESTED_UNVERIFIED (IS 99999) is NEVER present in primaryStandards');

console.log('\n====================================================');
console.log(`PHASE 4 TEST SUMMARY: ${passedTests} / ${totalTests} PASSED`);
console.log('====================================================');
if (passedTests === totalTests) {
  console.log('ALL PHASE 4 ADVISORY EXPORT VERIFICATION TESTS PASSED!');
} else {
  process.exit(1);
}
